# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
parameters:
    mzian.public_base_url: '%env(MZIAN_PUBLIC_BASE_URL)%'
    mzian.internal_base_url: '%env(MZIAN_INTERNAL_BASE_URL)%'
    mzian.mail_from: '%env(MZIAN_MAIL_FROM)%'
    mzian.admin_email: '%env(MZIAN_ADMIN_EMAIL)%'
    mzian.workspaces_dir: '%kernel.project_dir%/var/workspaces'
    mzian.repositories_dir: '%kernel.project_dir%/var/repositories'
    mzian.previews_dir: '%kernel.project_dir%/var/previews'
    mzian.application_templates_dir: '%kernel.project_dir%/resources/application-templates'
    mzian.catalog_file: '%kernel.project_dir%/config/mzian/catalog.yaml'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Entity/'
            - '../src/**/Enum/'
            - '../src/**/Dto/'
