<?php

/*
 * Generated by Mzian.net — loads the configuration (written at deployment) and
 * the schema of the application, then runs the management engine.
 */

declare(strict_types=1);

$configFile = __DIR__.'/config.php';
if (!is_file($configFile)) {
    http_response_code(503);
    exit('Application not configured: copy app/config.example.php to app/config.php.');
}
require __DIR__.'/MzianApp.php';

(new MzianApp(
    require $configFile,
    json_decode((string) file_get_contents(__DIR__.'/schema.json'), true, 512, JSON_THROW_ON_ERROR),
    __DIR__,
))->run();
