<?php

/*
 * Generated by Mzian.net — management application engine.
 *
 * Dependency-free (PHP >= 8.1, pdo_sqlite, mbstring). The entities, fields,
 * labels and public forms come from schema.json; secrets come from config.php
 * (written at deployment, never committed). Data lives in an SQLite file
 * outside the web root.
 *
 * Security: password_hash/verify, session fixation protection, CSRF tokens on
 * every admin form, login and public form throttling, prepared statements with
 * whitelisted columns, escaped output, CSV formula injection protection.
 */

declare(strict_types=1);

final class MzianApp
{
    private const LOGIN_ATTEMPTS = 5;
    private const LOGIN_WINDOW = 900;
    private const SUBMIT_ATTEMPTS = 10;
    private const SUBMIT_WINDOW = 600;

    private ?PDO $db = null;

    /**
     * @param array<string, mixed> $config
     * @param array<string, mixed> $schema
     */
    public function __construct(
        private readonly array $config,
        private readonly array $schema,
        private readonly string $configDir,
    ) {
    }

    public function run(): void
    {
        date_default_timezone_set((string) ($this->config['timezone'] ?? 'UTC'));
        $public = (string) ($_GET['public'] ?? '');
        if ('feed' === $public) {
            $this->feed((string) ($_GET['entity'] ?? ''));

            return;
        }
        if ('submit' === $public) {
            $this->submit((string) ($_GET['entity'] ?? ''));

            return;
        }

        $this->startSession();
        $action = (string) ($_GET['action'] ?? '');
        if ('login' === $action) {
            $this->login();

            return;
        }
        if (!$this->isLoggedIn()) {
            $this->redirect('?action=login');

            return;
        }
        if ('logout' === $action) {
            $this->requirePost();
            $_SESSION = [];
            session_regenerate_id(true);
            $this->redirect('?action=login');

            return;
        }
        if ('password' === $action) {
            $this->changePassword();

            return;
        }

        $entity = (string) ($_GET['entity'] ?? '');
        if ('' === $entity) {
            $this->dashboard();

            return;
        }
        $definition = $this->entity($entity);
        if (null === $definition) {
            $this->notFound();

            return;
        }
        match ($action) {
            'new', 'edit' => $this->form($entity, $definition, isset($_GET['id']) ? (int) $_GET['id'] : null),
            'delete' => $this->delete($entity),
            'export' => $this->export($entity, $definition),
            'print' => $this->printView($entity, $definition, (int) ($_GET['id'] ?? 0)),
            'calendar' => $this->calendar($entity, $definition),
            default => $this->listing($entity, $definition),
        };
    }

    // ------------------------------------------------------------------ public endpoints

    private function feed(string $entity): void
    {
        $definition = $this->entity($entity);
        if (null === $definition || true !== ($definition['public_list'] ?? false)) {
            $this->json(['error' => 'not_found'], 404);

            return;
        }
        $fields = array_values(array_intersect((array) ($definition['public_fields'] ?? []), $this->columns($definition)));
        $where = [];
        $params = [];
        foreach ((array) ($definition['public_filter'] ?? []) as $column => $value) {
            if (\in_array($column, $this->columns($definition), true)) {
                $where[] = '"'.$column.'" = ?';
                $params[] = (string) $value;
            }
        }
        $sql = 'SELECT id, '.implode(', ', array_map(static fn ($f) => '"'.$f.'"', $fields)).' FROM "'.$entity.'"'.($where ? ' WHERE '.implode(' AND ', $where) : '').' ORDER BY id ASC LIMIT 200';
        $statement = $this->db()->prepare($sql);
        $statement->execute($params);
        header('Cache-Control: public, max-age=60');
        $this->json(['entity' => $entity, 'items' => $statement->fetchAll(PDO::FETCH_ASSOC)]);
    }

    private function submit(string $entity): void
    {
        $definition = $this->entity($entity);
        $return = $this->safeReturn((string) ($_POST['_return'] ?? ''));
        if ('POST' !== ($_SERVER['REQUEST_METHOD'] ?? 'GET') || null === $definition || true !== ($definition['public_form'] ?? false)) {
            $this->notFound();

            return;
        }
        // Honeypot: bots fill every field.
        if ('' !== trim((string) ($_POST['website'] ?? ''))) {
            $this->redirect($return.'?sent=1#form');

            return;
        }
        if (!$this->throttle('submit:'.$this->ip(), self::SUBMIT_ATTEMPTS, self::SUBMIT_WINDOW)) {
            $this->redirect($return.'?error=throttled#form');

            return;
        }
        $allowed = (array) ($definition['form_fields'] ?? []);
        $fields = array_values(array_filter($definition['fields'], static fn ($f) => \in_array($f['name'], $allowed, true)));
        [$values, $errors] = $this->validate($fields, $_POST);
        if ([] !== $errors) {
            $this->redirect($return.'?error=invalid#form');

            return;
        }
        foreach ((array) ($definition['form_defaults'] ?? []) as $column => $value) {
            $values[$column] = (string) $value;
        }
        $id = $this->insert($entity, $definition, $values);
        $this->notify($entity, $definition, $values, $id);
        $this->redirect($return.'?sent=1#form');
    }

    // ------------------------------------------------------------------ admin pages

    private function login(): void
    {
        $error = null;
        if ('POST' === ($_SERVER['REQUEST_METHOD'] ?? 'GET')) {
            $this->requireCsrf();
            $key = 'login:'.$this->ip();
            if (!$this->throttle($key, self::LOGIN_ATTEMPTS, self::LOGIN_WINDOW, false)) {
                $error = $this->t('too_many_attempts');
            } elseif (hash_equals(mb_strtolower((string) $this->config['admin_email']), mb_strtolower(trim((string) ($_POST['email'] ?? ''))))
                && password_verify((string) ($_POST['password'] ?? ''), $this->passwordHash())) {
                session_regenerate_id(true);
                $_SESSION['admin'] = true;
                $_SESSION['login_at'] = time();
                $this->db()->prepare('DELETE FROM _throttle WHERE key = ?')->execute([$key]);
                $this->redirect('./');

                return;
            } else {
                $this->throttle($key, self::LOGIN_ATTEMPTS, self::LOGIN_WINDOW);
                $error = $this->t('invalid_credentials');
            }
        }
        $html = '<form method="post" class="card narrow">'
            .'<h1>'.$this->e((string) $this->schema['app']['name']).'</h1>'
            .($error ? '<p class="alert error">'.$this->e($error).'</p>' : '')
            .$this->csrfField()
            .'<label>'.$this->t('email').'<input type="email" name="email" required autocomplete="username"></label>'
            .'<label>'.$this->t('password').'<input type="password" name="password" required autocomplete="current-password"></label>'
            .'<button class="primary">'.$this->t('sign_in').'</button></form>';
        $this->page($this->t('sign_in'), $html, false, null !== $error ? 422 : 200);
    }

    private function changePassword(): void
    {
        $message = null;
        if ('POST' === ($_SERVER['REQUEST_METHOD'] ?? 'GET')) {
            $this->requireCsrf();
            $new = (string) ($_POST['new_password'] ?? '');
            if (!password_verify((string) ($_POST['current_password'] ?? ''), $this->passwordHash())) {
                $message = ['error', $this->t('invalid_credentials')];
            } elseif (mb_strlen($new) < 12) {
                $message = ['error', $this->t('password_too_short')];
            } else {
                $this->db()->prepare('INSERT OR REPLACE INTO _settings (key, value) VALUES (?, ?)')->execute(['admin_password_hash', password_hash($new, PASSWORD_DEFAULT)]);
                session_regenerate_id(true);
                $message = ['success', $this->t('password_changed')];
            }
        }
        $html = '<form method="post" class="card narrow">'.$this->csrfField()
            .($message ? '<p class="alert '.$message[0].'">'.$this->e($message[1]).'</p>' : '')
            .'<label>'.$this->t('current_password').'<input type="password" name="current_password" required autocomplete="current-password"></label>'
            .'<label>'.$this->t('new_password').'<input type="password" name="new_password" required minlength="12" autocomplete="new-password"></label>'
            .'<button class="primary">'.$this->t('save').'</button></form>';
        $this->page($this->t('change_password'), $html);
    }

    private function dashboard(): void
    {
        $cards = '';
        $stats = '';
        foreach ($this->schema['entities'] as $code => $definition) {
            $count = (int) $this->db()->query('SELECT COUNT(*) FROM "'.$code.'"')->fetchColumn();
            $detail = '';
            if (\in_array('status', $this->columns($definition), true)) {
                $rows = $this->db()->query('SELECT status, COUNT(*) AS c FROM "'.$code.'" GROUP BY status')->fetchAll(PDO::FETCH_KEY_PAIR);
                $options = $this->field($definition, 'status')['options'] ?? [];
                foreach ($rows as $status => $total) {
                    $detail .= '<span class="badge">'.$this->e((string) ($options[$status] ?? $status)).': '.(int) $total.'</span> ';
                }
            }
            $cards .= '<a class="card stat" href="?entity='.$this->e($code).'"><span class="icon">'.$this->e((string) ($definition['icon'] ?? '📁')).'</span><strong>'.$count.'</strong><span>'.$this->e((string) $definition['label']).'</span><span class="muted">'.$detail.'</span></a>';
            if (true === ($definition['stats'] ?? false)) {
                $stats .= $this->monthlyStats($code, $definition);
            }
        }
        $html = '<div class="grid">'.$cards.'</div>'.('' !== $stats ? '<h2>'.$this->t('statistics').'</h2><div class="grid">'.$stats.'</div>' : '');
        $this->page($this->t('dashboard'), $html);
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function listing(string $entity, array $definition): void
    {
        $query = trim((string) ($_GET['q'] ?? ''));
        $columns = (array) ($definition['list'] ?? [$definition['title']]);
        $searchable = array_values(array_filter($definition['fields'], static fn ($f) => \in_array($f['type'], ['text', 'email', 'tel', 'textarea'], true)));
        $sql = 'SELECT * FROM "'.$entity.'"';
        $params = [];
        if ('' !== $query && [] !== $searchable) {
            $sql .= ' WHERE '.implode(' OR ', array_map(static fn ($f) => '"'.$f['name'].'" LIKE ?', $searchable));
            $params = array_fill(0, \count($searchable), '%'.$query.'%');
        }
        $statement = $this->db()->prepare($sql.' ORDER BY id DESC LIMIT 500');
        $statement->execute($params);
        $rows = $statement->fetchAll(PDO::FETCH_ASSOC);

        $head = implode('', array_map(fn ($c) => '<th>'.$this->e((string) ($this->field($definition, $c)['label'] ?? $c)).'</th>', $columns));
        $body = '';
        foreach ($rows as $row) {
            $cells = implode('', array_map(fn ($c) => '<td>'.$this->display($definition, $c, $row[$c] ?? null).'</td>', $columns));
            $actions = '<a href="?entity='.$this->e($entity).'&amp;action=edit&amp;id='.(int) $row['id'].'">'.$this->t('edit').'</a>';
            if (true === ($definition['printable'] ?? false)) {
                $actions .= ' · <a href="?entity='.$this->e($entity).'&amp;action=print&amp;id='.(int) $row['id'].'" target="_blank">'.$this->t('print').'</a>';
            }
            $body .= '<tr>'.$cells.'<td class="actions">'.$actions.'</td></tr>';
        }
        if ('' === $body) {
            $body = '<tr><td colspan="'.(\count($columns) + 1).'" class="muted">'.$this->t('no_records').'</td></tr>';
        }
        $tools = '<div class="toolbar"><form method="get"><input type="hidden" name="entity" value="'.$this->e($entity).'"><input type="search" name="q" value="'.$this->e($query).'" placeholder="'.$this->t('search').'"></form>'
            .'<a class="button primary" href="?entity='.$this->e($entity).'&amp;action=new">+ '.$this->t('new').'</a>'
            .(null !== ($definition['calendar'] ?? null) ? '<a class="button" href="?entity='.$this->e($entity).'&amp;action=calendar">'.$this->t('calendar').'</a>' : '')
            .'<a class="button" href="?entity='.$this->e($entity).'&amp;action=export">'.$this->t('export_csv').'</a></div>';
        $this->page((string) $definition['label'], $tools.'<div class="table"><table><thead><tr>'.$head.'<th></th></tr></thead><tbody>'.$body.'</tbody></table></div>');
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function form(string $entity, array $definition, ?int $id): void
    {
        $row = [];
        if (null !== $id) {
            $statement = $this->db()->prepare('SELECT * FROM "'.$entity.'" WHERE id = ?');
            $statement->execute([$id]);
            $row = $statement->fetch(PDO::FETCH_ASSOC) ?: null;
            if (null === $row) {
                $this->notFound();

                return;
            }
        }
        $errors = [];
        if ('POST' === ($_SERVER['REQUEST_METHOD'] ?? 'GET')) {
            $this->requireCsrf();
            [$values, $errors] = $this->validate($definition['fields'], $_POST);
            if ([] === $errors) {
                if (null === $id) {
                    $this->insert($entity, $definition, $values);
                } else {
                    $values['updated_at'] = date('c');
                    $sets = implode(', ', array_map(static fn ($c) => '"'.$c.'" = ?', array_keys($values)));
                    $this->db()->prepare('UPDATE "'.$entity.'" SET '.$sets.' WHERE id = ?')->execute([...array_values($values), $id]);
                }
                $_SESSION['flash'] = $this->t('saved');
                $this->redirect('?entity='.rawurlencode($entity));

                return;
            }
            $row = array_merge($row ?? [], array_map(static fn ($v) => \is_scalar($v) ? (string) $v : '', $_POST));
        }

        $inputs = '';
        foreach ($definition['fields'] as $field) {
            $inputs .= $this->input($field, $row[$field['name']] ?? ($field['default'] ?? null), $errors[$field['name']] ?? null);
        }
        $html = '<form method="post" class="card">'.$this->csrfField().$inputs
            .'<div class="toolbar"><button class="primary">'.$this->t('save').'</button><a class="button" href="?entity='.$this->e($entity).'">'.$this->t('cancel').'</a></div></form>';
        if (null !== $id) {
            $html .= '<form method="post" action="?entity='.$this->e($entity).'&amp;action=delete&amp;id='.$id.'" onsubmit="return confirm(\''.$this->e($this->t('confirm_delete')).'\')" class="danger-zone">'
                .$this->csrfField().'<button class="danger">'.$this->t('delete').'</button></form>';
        }
        $this->page((null === $id ? $this->t('new') : $this->t('edit')).' — '.$definition['singular'], $html, true, [] === $errors ? 200 : 422);
    }

    private function delete(string $entity): void
    {
        $this->requirePost();
        $this->requireCsrf();
        $this->db()->prepare('DELETE FROM "'.$entity.'" WHERE id = ?')->execute([(int) ($_GET['id'] ?? 0)]);
        $_SESSION['flash'] = $this->t('deleted');
        $this->redirect('?entity='.rawurlencode($entity));
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function export(string $entity, array $definition): void
    {
        $columns = ['id', ...$this->columns($definition), 'created_at'];
        header('Content-Type: text/csv; charset=utf-8');
        header('Content-Disposition: attachment; filename="'.$entity.'-'.date('Y-m-d').'.csv"');
        $out = fopen('php://output', 'w');
        fwrite($out, "\xEF\xBB\xBF");
        fputcsv($out, $columns, ',', '"', '\\');
        foreach ($this->db()->query('SELECT * FROM "'.$entity.'" ORDER BY id') as $row) {
            fputcsv($out, array_map(static function ($column) use ($row): string {
                $value = (string) ($row[$column] ?? '');

                return preg_match('/^[=+\-@\t\r]/', $value) ? "'".$value : $value; // CSV injection
            }, $columns), ',', '"', '\\');
        }
        fclose($out);
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function printView(string $entity, array $definition, int $id): void
    {
        $statement = $this->db()->prepare('SELECT * FROM "'.$entity.'" WHERE id = ?');
        $statement->execute([$id]);
        $row = $statement->fetch(PDO::FETCH_ASSOC);
        if (false === $row || true !== ($definition['printable'] ?? false)) {
            $this->notFound();

            return;
        }
        $lines = '';
        foreach ($definition['fields'] as $field) {
            $lines .= '<tr><th>'.$this->e((string) $field['label']).'</th><td>'.$this->display($definition, $field['name'], $row[$field['name']] ?? null).'</td></tr>';
        }
        $app = $this->schema['app'];
        $html = '<div class="print"><header><h1>'.$this->e((string) $app['name']).'</h1><p>'.$this->e((string) $definition['singular']).' #'.$id.' — '.date('d/m/Y').'</p></header>'
            .'<table class="print-table">'.$lines.'</table>'
            .'<div class="signatures"><p>'.$this->t('signature_company').'</p><p>'.$this->t('signature_customer').'</p></div>'
            .'<button class="primary no-print" onclick="window.print()">'.$this->t('print').'</button></div>';
        $this->page($definition['singular'].' #'.$id, $html, false);
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function calendar(string $entity, array $definition): void
    {
        $column = (string) ($definition['calendar'] ?? '');
        if (!\in_array($column, $this->columns($definition), true)) {
            $this->notFound();

            return;
        }
        $month = preg_match('/^\d{4}-\d{2}$/', (string) ($_GET['month'] ?? '')) ? (string) $_GET['month'] : date('Y-m');
        $first = new DateTimeImmutable($month.'-01');
        $statement = $this->db()->prepare('SELECT id, "'.$column.'" AS day, "'.$definition['title'].'" AS title FROM "'.$entity.'" WHERE "'.$column.'" LIKE ? ORDER BY "'.$column.'"');
        $statement->execute([$month.'%']);
        $byDay = [];
        foreach ($statement->fetchAll(PDO::FETCH_ASSOC) as $item) {
            $byDay[substr((string) $item['day'], 0, 10)][] = $item;
        }
        $cells = str_repeat('<div class="day empty"></div>', (int) $first->format('N') - 1);
        for ($day = 1; $day <= (int) $first->format('t'); ++$day) {
            $date = $first->format('Y-m-').str_pad((string) $day, 2, '0', STR_PAD_LEFT);
            $items = '';
            foreach ($byDay[$date] ?? [] as $item) {
                $items .= '<a href="?entity='.$this->e($entity).'&amp;action=edit&amp;id='.(int) $item['id'].'">'.$this->e((string) $item['title']).'</a>';
            }
            $cells .= '<div class="day'.($date === date('Y-m-d') ? ' today' : '').'"><span>'.$day.'</span>'.$items.'</div>';
        }
        $nav = '<div class="toolbar"><a class="button" href="?entity='.$this->e($entity).'&amp;action=calendar&amp;month='.$first->modify('-1 month')->format('Y-m').'">← '.$this->t('previous').'</a>'
            .'<strong>'.$first->format('m/Y').'</strong>'
            .'<a class="button" href="?entity='.$this->e($entity).'&amp;action=calendar&amp;month='.$first->modify('+1 month')->format('Y-m').'">'.$this->t('next').' →</a></div>';
        $this->page($definition['label'].' — '.$this->t('calendar'), $nav.'<div class="calendar">'.$cells.'</div>');
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function monthlyStats(string $entity, array $definition): string
    {
        $rows = $this->db()->query('SELECT substr(created_at, 1, 7) AS month, COUNT(*) AS c FROM "'.$entity.'" WHERE created_at >= \''.date('Y-m-01', strtotime('-5 months')).'\' GROUP BY month ORDER BY month')->fetchAll(PDO::FETCH_KEY_PAIR);
        $max = max([1, ...array_values($rows)]);
        $bars = '';
        for ($i = 5; $i >= 0; --$i) {
            $month = date('Y-m', strtotime('-'.$i.' months', strtotime(date('Y-m-01'))));
            $value = (int) ($rows[$month] ?? 0);
            $bars .= '<div class="bar"><span style="height:'.(int) round($value * 100 / $max).'%"></span><small>'.substr($month, 5).'</small><b>'.$value.'</b></div>';
        }

        return '<div class="card"><h3>'.$this->e((string) $definition['label']).' <small class="muted">'.$this->t('last_months').'</small></h3><div class="bars">'.$bars.'</div></div>';
    }

    // ------------------------------------------------------------------ data

    private function db(): PDO
    {
        if (null !== $this->db) {
            return $this->db;
        }
        $dir = (string) ($this->config['data_dir'] ?? 'data');
        if (!str_starts_with($dir, '/')) {
            $dir = $this->configDir.'/'.$dir;
        }
        if (!is_dir($dir) && !mkdir($dir, 0770, true) && !is_dir($dir)) {
            throw new RuntimeException('Cannot create the data directory.');
        }
        $this->db = new PDO('sqlite:'.$dir.'/app.sqlite', null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
        $this->db->exec('PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON;');
        $this->migrate();

        return $this->db;
    }

    private function migrate(): void
    {
        $db = $this->db;
        $db->exec('CREATE TABLE IF NOT EXISTS _settings (key TEXT PRIMARY KEY, value TEXT)');
        $db->exec('CREATE TABLE IF NOT EXISTS _throttle (key TEXT NOT NULL, at INTEGER NOT NULL)');
        foreach ($this->schema['entities'] as $code => $definition) {
            $exists = (bool) $db->query("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ".$db->quote($code))->fetchColumn();
            if (!$exists) {
                $columns = array_map(fn ($f) => '"'.$f['name'].'" '.(\in_array($f['type'], ['number', 'money'], true) ? 'NUMERIC' : 'TEXT'), $definition['fields']);
                $db->exec('CREATE TABLE "'.$code.'" (id INTEGER PRIMARY KEY AUTOINCREMENT, '.implode(', ', $columns).', created_at TEXT NOT NULL, updated_at TEXT)');
                foreach ((array) ($definition['seed'] ?? []) as $seed) {
                    $this->insert($code, $definition, array_intersect_key(array_map('strval', $seed), array_flip($this->columns($definition))));
                }
                continue;
            }
            $existing = array_column($db->query('PRAGMA table_info("'.$code.'")')->fetchAll(PDO::FETCH_ASSOC), 'name');
            foreach ($definition['fields'] as $field) {
                if (!\in_array($field['name'], $existing, true)) {
                    $db->exec('ALTER TABLE "'.$code.'" ADD COLUMN "'.$field['name'].'" TEXT');
                }
            }
        }
    }

    /**
     * @param array<string, mixed>  $definition
     * @param array<string, string> $values
     */
    private function insert(string $entity, array $definition, array $values): int
    {
        $values['created_at'] = date('c');
        $columns = implode(', ', array_map(static fn ($c) => '"'.$c.'"', array_keys($values)));
        $this->db()->prepare('INSERT INTO "'.$entity.'" ('.$columns.') VALUES ('.implode(', ', array_fill(0, \count($values), '?')).')')->execute(array_values($values));

        return (int) $this->db()->lastInsertId();
    }

    /**
     * @param list<array<string, mixed>> $fields
     * @param array<string, mixed>       $input
     *
     * @return array{0: array<string, string>, 1: array<string, string>}
     */
    private function validate(array $fields, array $input): array
    {
        $values = [];
        $errors = [];
        foreach ($fields as $field) {
            $name = $field['name'];
            $raw = $input[$name] ?? null;
            $value = 'boolean' === $field['type'] ? (empty($raw) ? '0' : '1') : trim(\is_scalar($raw) ? (string) $raw : '');
            if (mb_strlen($value) > ('textarea' === $field['type'] ? 5000 : 255)) {
                $errors[$name] = $this->t('too_long');
            } elseif ('' === $value && true === ($field['required'] ?? false)) {
                $errors[$name] = $this->t('required');
            } elseif ('' !== $value) {
                $valid = match ($field['type']) {
                    'email' => false !== filter_var($value, FILTER_VALIDATE_EMAIL),
                    'number' => is_numeric($value),
                    'money' => (bool) preg_match('/^\d+([.,]\d{1,2})?$/', $value),
                    'date' => (bool) preg_match('/^\d{4}-\d{2}-\d{2}$/', $value),
                    'time' => (bool) preg_match('/^\d{2}:\d{2}$/', $value),
                    'select' => \array_key_exists($value, (array) ($field['options'] ?? [])),
                    default => true,
                };
                if (!$valid) {
                    $errors[$name] = $this->t('invalid_value');
                }
                if ('money' === $field['type']) {
                    $value = number_format((float) str_replace(',', '.', $value), 2, '.', '');
                }
            }
            $values[$name] = $value;
        }

        return [$values, $errors];
    }

    /**
     * @param array<string, mixed>  $definition
     * @param array<string, string> $values
     */
    private function notify(string $entity, array $definition, array $values, int $id): void
    {
        $owner = (string) ($this->config['notify_email'] ?? '');
        if (!\function_exists('mail')) {
            return;
        }
        $summary = '';
        foreach ($definition['fields'] as $field) {
            if (isset($values[$field['name']]) && '' !== $values[$field['name']]) {
                $summary .= $field['label'].': '.$values[$field['name']]."\n";
            }
        }
        $headers = 'Content-Type: text/plain; charset=UTF-8';
        if ('' !== $owner) {
            @mail($owner, '['.$this->schema['app']['name'].'] '.$definition['singular'].' #'.$id, $summary, $headers);
        }
        $customer = (string) ($values['email'] ?? '');
        if (true === ($definition['confirm_email'] ?? false) && false !== filter_var($customer, FILTER_VALIDATE_EMAIL)) {
            @mail($customer, $this->schema['app']['name'].' — '.$this->t('confirmation_subject'), $this->t('confirmation_body')."\n\n".$summary, $headers);
        }
    }

    private function throttle(string $key, int $limit, int $window, bool $record = true): bool
    {
        $db = $this->db();
        $db->prepare('DELETE FROM _throttle WHERE at < ?')->execute([time() - 86400]);
        $count = $db->prepare('SELECT COUNT(*) FROM _throttle WHERE key = ? AND at > ?');
        $count->execute([$key, time() - $window]);
        if ((int) $count->fetchColumn() >= $limit) {
            return false;
        }
        if ($record) {
            $db->prepare('INSERT INTO _throttle (key, at) VALUES (?, ?)')->execute([$key, time()]);
        }

        return true;
    }

    private function passwordHash(): string
    {
        $statement = $this->db()->prepare('SELECT value FROM _settings WHERE key = ?');
        $statement->execute(['admin_password_hash']);

        return (string) ($statement->fetchColumn() ?: $this->config['admin_password_hash']);
    }

    // ------------------------------------------------------------------ helpers

    /**
     * @return array<string, mixed>|null
     */
    private function entity(string $code): ?array
    {
        return $this->schema['entities'][$code] ?? null;
    }

    /**
     * @param array<string, mixed> $definition
     *
     * @return list<string>
     */
    private function columns(array $definition): array
    {
        return array_column($definition['fields'], 'name');
    }

    /**
     * @param array<string, mixed> $definition
     *
     * @return array<string, mixed>|null
     */
    private function field(array $definition, string $name): ?array
    {
        foreach ($definition['fields'] as $field) {
            if ($field['name'] === $name) {
                return $field;
            }
        }

        return null;
    }

    /**
     * @param array<string, mixed> $definition
     */
    private function display(array $definition, string $column, mixed $value): string
    {
        $field = $this->field($definition, $column);
        $value = (string) ($value ?? '');

        return match ($field['type'] ?? 'text') {
            'boolean' => '1' === $value ? '✓' : '—',
            'select' => $this->e((string) ($field['options'][$value] ?? $value)),
            'money' => '' === $value ? '' : $this->e(number_format((float) $value, 2, ',', ' ').' '.($this->schema['app']['currency'] ?? '')),
            'textarea' => nl2br($this->e(mb_strimwidth($value, 0, 400, '…'))),
            default => $this->e($value),
        };
    }

    /**
     * @param array<string, mixed> $field
     */
    private function input(array $field, mixed $value, ?string $error): string
    {
        $name = $this->e((string) $field['name']);
        $label = $this->e((string) $field['label']).(true === ($field['required'] ?? false) ? ' *' : '');
        $value = (string) ($value ?? '');
        $required = true === ($field['required'] ?? false) ? ' required' : '';
        $control = match ($field['type']) {
            'textarea' => '<textarea name="'.$name.'" rows="4"'.$required.'>'.$this->e($value).'</textarea>',
            'select' => '<select name="'.$name.'"'.$required.'><option value=""></option>'.implode('', array_map(fn ($k, $v) => '<option value="'.$this->e((string) $k).'"'.((string) $k === $value ? ' selected' : '').'>'.$this->e((string) $v).'</option>', array_keys((array) $field['options']), (array) $field['options'])).'</select>',
            'boolean' => '<input type="checkbox" name="'.$name.'" value="1"'.('1' === $value ? ' checked' : '').'>',
            default => '<input type="'.match ($field['type']) {
                'email' => 'email', 'tel' => 'tel', 'number' => 'number', 'money' => 'text" inputmode="decimal', 'date' => 'date', 'time' => 'time', default => 'text',
            }.'" name="'.$name.'" value="'.$this->e($value).'"'.$required.'>',
        };

        return '<label class="'.('boolean' === $field['type'] ? 'check' : '').'">'.$label.$control.(null !== $error ? '<span class="error">'.$this->e($error).'</span>' : '').'</label>';
    }

    private function t(string $key): string
    {
        return (string) ($this->schema['ui'][$key] ?? $key);
    }

    private function e(string $value): string
    {
        return htmlspecialchars($value, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
    }

    private function startSession(): void
    {
        session_name('MZIANADMIN');
        session_set_cookie_params([
            'lifetime' => 0,
            'path' => \dirname((string) ($_SERVER['SCRIPT_NAME'] ?? '/')).'/',
            'secure' => 'on' === ($_SERVER['HTTPS'] ?? '') || 'https' === ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? ''),
            'httponly' => true,
            'samesite' => 'Lax',
        ]);
        session_start();
        $_SESSION['csrf'] ??= bin2hex(random_bytes(32));
        // Idle sessions expire after 8 hours.
        if (isset($_SESSION['login_at']) && time() - (int) $_SESSION['login_at'] > 28800) {
            $_SESSION = ['csrf' => bin2hex(random_bytes(32))];
        }
    }

    private function isLoggedIn(): bool
    {
        return true === ($_SESSION['admin'] ?? false);
    }

    private function csrfField(): string
    {
        return '<input type="hidden" name="_csrf" value="'.$this->e((string) $_SESSION['csrf']).'">';
    }

    private function requireCsrf(): void
    {
        if (!hash_equals((string) ($_SESSION['csrf'] ?? ''), (string) ($_POST['_csrf'] ?? ''))) {
            http_response_code(403);
            exit($this->t('csrf_error'));
        }
    }

    private function requirePost(): void
    {
        if ('POST' !== ($_SERVER['REQUEST_METHOD'] ?? 'GET')) {
            http_response_code(405);
            exit;
        }
    }

    private function ip(): string
    {
        return (string) ($_SERVER['REMOTE_ADDR'] ?? 'unknown');
    }

    private function safeReturn(string $path): string
    {
        return 1 === preg_match('#^(\.\./)*([a-z]{2}/)?[a-z0-9_-]+\.html$#', $path) ? $path : '../index.html';
    }

    private function redirect(string $location): void
    {
        header('Location: '.$location, true, 302);
    }

    /**
     * @param array<string, mixed> $data
     */
    private function json(array $data, int $status = 200): void
    {
        http_response_code($status);
        header('Content-Type: application/json; charset=utf-8');
        echo json_encode($data, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
    }

    private function notFound(): void
    {
        $this->page('404', '<p class="card">'.$this->t('not_found').'</p>', $this->isLoggedIn(), 404);
    }

    private function page(string $title, string $content, bool $navigation = true, int $status = 200): void
    {
        http_response_code($status);
        header('Content-Type: text/html; charset=utf-8');
        header('X-Frame-Options: DENY');
        header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'none'");
        $app = $this->schema['app'];
        $menu = '';
        if ($navigation && $this->isLoggedIn()) {
            $current = (string) ($_GET['entity'] ?? '');
            $menu .= '<a href="./"'.('' === $current ? ' class="active"' : '').'>'.$this->t('dashboard').'</a>';
            foreach ($this->schema['entities'] as $code => $definition) {
                $menu .= '<a href="?entity='.$this->e($code).'"'.($code === $current ? ' class="active"' : '').'>'.$this->e(($definition['icon'] ?? '').' '.$definition['label']).'</a>';
            }
            $menu .= '<a href="?action=password">'.$this->t('change_password').'</a>'
                .'<a href="'.$this->e((string) ($app['site_url'] ?? '../')).'" target="_blank">'.$this->t('view_site').' ↗</a>'
                .'<form method="post" action="?action=logout">'.$this->csrfField().'<button class="link">'.$this->t('logout').'</button></form>';
        }
        $flash = '';
        if (isset($_SESSION['flash'])) {
            $flash = '<p class="alert success">'.$this->e((string) $_SESSION['flash']).'</p>';
            unset($_SESSION['flash']);
        }
        $primary = preg_match('/^#[0-9a-fA-F]{6}$/', (string) ($app['primary'] ?? '')) ? $app['primary'] : '#4c3fe6';
        echo '<!doctype html><html lang="'.$this->e((string) $app['locale']).'" dir="'.$this->e((string) ($app['dir'] ?? 'ltr')).'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex, nofollow">'
            .'<title>'.$this->e($title.' — '.$app['name']).'</title><style>'.self::css($primary).'</style></head><body>'
            .('' !== $menu ? '<nav class="side"><strong class="brand">'.$this->e((string) $app['name']).'</strong>'.$menu.'</nav>' : '')
            .'<main><h1 class="title">'.$this->e($title).'</h1>'.$flash.$content.'</main></body></html>';
    }

    private static function css(string $primary): string
    {
        return ':root{--p:'.$primary.';--ink:#0f172a;--muted:#64748b;--line:#e2e8f0;--bg:#f8fafc}*{box-sizing:border-box}body{margin:0;font:15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,"Noto Sans Arabic",sans-serif;color:var(--ink);background:var(--bg);display:flex;min-height:100vh}'
            .'nav.side{width:230px;background:#0f172a;color:#cbd5e1;padding:1rem;display:flex;flex-direction:column;gap:.25rem}nav.side a,nav.side .link{color:#cbd5e1;text-decoration:none;padding:.45rem .6rem;border-radius:.5rem;background:none;border:0;font:inherit;text-align:start;cursor:pointer}nav.side a.active,nav.side a:hover{background:#1e293b;color:#fff}.brand{color:#fff;margin-bottom:.75rem}'
            .'main{flex:1;padding:1.5rem;max-width:1100px;min-width:0}.title{font-size:1.4rem;margin:0 0 1rem}.card{background:#fff;border:1px solid var(--line);border-radius:14px;padding:1rem;margin-bottom:1rem}.narrow{max-width:420px;margin:3rem auto}'
            .'label{display:block;margin-bottom:.8rem;font-weight:600;font-size:.9rem}label.check{display:flex;gap:.5rem;align-items:center}input,select,textarea{display:block;width:100%;margin-top:.25rem;padding:.6rem .7rem;border:1px solid #cbd5e1;border-radius:10px;font:inherit}label.check input{width:auto;margin:0}'
            .'button,.button{display:inline-block;padding:.55rem .9rem;border-radius:10px;border:1px solid var(--line);background:#fff;color:var(--ink);font:inherit;font-weight:600;text-decoration:none;cursor:pointer}.primary{background:var(--p);border-color:var(--p);color:#fff}.danger{background:#e11d48;border-color:#e11d48;color:#fff}'
            .'.toolbar{display:flex;gap:.5rem;flex-wrap:wrap;align-items:center;margin-bottom:1rem}.toolbar form{flex:1;min-width:200px}.toolbar input{margin:0}.table{overflow-x:auto;background:#fff;border:1px solid var(--line);border-radius:14px}table{width:100%;border-collapse:collapse}th,td{padding:.6rem .75rem;border-bottom:1px solid var(--line);text-align:start;vertical-align:top}th{font-size:.8rem;color:var(--muted);text-transform:uppercase}.actions{white-space:nowrap}.actions a{color:var(--p)}'
            .'.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:1rem}.stat{display:flex;flex-direction:column;text-decoration:none;color:inherit}.stat strong{font-size:1.8rem}.icon{font-size:1.4rem}.muted{color:var(--muted);font-size:.85rem}.badge{display:inline-block;background:#eef2ff;border-radius:999px;padding:0 .5rem;margin:.1rem 0;font-size:.75rem}'
            .'.alert{padding:.7rem 1rem;border-radius:10px}.alert.success{background:#ecfdf5;color:#065f46}.alert.error,.error{color:#be123c}.alert.error{background:#fff1f2}.error{display:block;font-weight:400}.danger-zone{margin-top:1rem}'
            .'.calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:.25rem}.day{background:#fff;border:1px solid var(--line);border-radius:8px;min-height:80px;padding:.3rem;font-size:.8rem}.day a{display:block;color:var(--p);text-decoration:none;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.day.empty{background:none;border:0}.day.today{border-color:var(--p)}'
            .'.bars{display:flex;gap:.5rem;align-items:flex-end;height:120px}.bar{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;height:100%}.bar span{width:100%;background:var(--p);border-radius:6px 6px 0 0;min-height:2px}.bar small{color:var(--muted)}'
            .'.print{max-width:800px;margin:auto;background:#fff;padding:2rem}.print-table th{width:35%}.signatures{display:flex;justify-content:space-between;margin-top:4rem}.signatures p{border-top:1px solid var(--ink);padding-top:.5rem;width:40%}'
            .'@media print{nav.side,.no-print,.title{display:none}body{background:#fff}main{padding:0}}@media (max-width:760px){body{flex-direction:column}nav.side{width:auto;flex-direction:row;flex-wrap:wrap}}';
    }
}
