<?php

declare(strict_types=1);

namespace App\Agent\Agents;

use App\Agent\AgentContext;
use App\Agent\AgentInterface;
use App\Agent\AgentPermission;
use App\Agent\AgentResult;
use App\Agent\Budget\BudgetGuard;
use App\Agent\Exception\AgentException;
use App\Agent\Exception\NeedsAdminException;
use App\Delivery\CredentialService;
use App\Development\Content\ContentWriter;
use App\Development\Generator\ApplicationGenerator;
use App\Development\Generator\GenerationRequest;
use App\Development\Generator\TemplateCatalog;
use App\Development\Repository\RepositoryInfo;
use App\Development\Repository\RepositoryProviderInterface;
use App\Project\Entity\Project;
use App\Project\Enum\CostCategory;
use App\Project\Enum\PipelineStep;
use App\Provider\Entity\Provider;
use App\Provider\Enum\ProviderType;
use App\Provider\ProviderRegistry;
use App\Shared\Settings\SettingsService;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Container\ContainerInterface;
use Symfony\Component\DependencyInjection\Attribute\Autowire;
use Symfony\Component\DependencyInjection\Attribute\AutowireLocator;

/**
 * Development Agent:
 *  - create_project: the customer's Git repository (mzian-client-<id>);
 *  - generate_application: website copy (AI, validated, deterministic fallback),
 *    application generated from the solution's template, administrator account
 *    (password stored encrypted), commit of the sources.
 * Features no template implements are listed in the manifest, never faked.
 */
final readonly class DevelopmentAgent implements AgentInterface
{
    public function __construct(
        private ProviderRegistry $providers,
        #[AutowireLocator('mzian.repository_provider', defaultIndexMethod: 'getDriver')]
        private ContainerInterface $repositories,
        private ApplicationGenerator $generator,
        private TemplateCatalog $templates,
        private ContentWriter $writer,
        private BudgetGuard $budget,
        private CredentialService $credentials,
        private SettingsService $settings,
        private EntityManagerInterface $em,
        #[Autowire('%mzian.builds_dir%')]
        private string $buildsDir,
        #[Autowire('%env(MZIAN_APPS_PUBLIC_URL)%')]
        private string $appsUrl,
    ) {
    }

    public static function getCode(): string
    {
        return 'development';
    }

    public static function step(): PipelineStep
    {
        return PipelineStep::Development;
    }

    public static function requiredPermissions(string $operation): array
    {
        return 'create_project' === $operation
            ? [AgentPermission::REPOSITORY_WRITE]
            : [AgentPermission::APPLICATION_GENERATE, AgentPermission::AI_CONTENT, AgentPermission::REPOSITORY_WRITE, AgentPermission::CREDENTIALS_STORE, AgentPermission::BUDGET_SPEND];
    }

    public function execute(AgentContext $context): AgentResult
    {
        return match ($context->operation) {
            'create_project' => $this->createRepository($context),
            'generate_application' => $this->generate($context),
            default => throw AgentException::permanent('Unknown development operation '.$context->operation),
        };
    }

    private function createRepository(AgentContext $context): AgentResult
    {
        $project = $context->project;
        [$provider, $driver] = $this->repository($project);
        $repository = $driver->createRepository($provider, 'mzian-client-'.$project->getId(), $project->getName().' — generated by Mzian.net');
        $project->setRepositoryUrl($repository->url);
        $this->em->flush();
        $context->log('Repository ready', ['repository' => $repository->fullName, 'provider' => $provider->getCode()]);

        return new AgentResult('Repository '.$repository->fullName.' ready.', ['repository' => $repository->toArray(), 'repository_provider' => $provider->getCode()]);
    }

    private function generate(AgentContext $context): AgentResult
    {
        $project = $context->project;
        $template = (string) $project->getApplicationTemplate();
        if (!$this->templates->has($template)) {
            throw new NeedsAdminException(\sprintf('No application template "%s": this project needs a developer.', $template));
        }
        $repositoryData = $context->task->getOutput()['repository'] ?? null;
        if (!\is_array($repositoryData)) {
            throw AgentException::transient('The repository is not created yet.');
        }

        $baseFeatures = (array) ($this->templates->template($template)['base_features'] ?? []);
        $multilingual = \in_array('multilingual', [...$baseFeatures, ...$project->getFeatures()], true);
        $languages = $multilingual ? array_values(array_unique([$project->getLocale(), ...TemplateCatalog::LOCALES])) : [$project->getLocale()];
        $content = [];
        $fallback = false;
        foreach ($languages as $language) {
            $written = $this->writer->write($project, $language);
            $content[$language] = $written['content'];
            $fallback = $fallback || $written['fallback'];
            $cost = (int) ($written['usage']['cost_cents'] ?? 0);
            if ($cost > 0) {
                $this->budget->authorize($project, CostCategory::Ai, $cost, 'Website copy ('.$language.')');
                $this->budget->record($project, CostCategory::Ai, $cost, 'USD', 'AI website copy ('.$language.')', (string) ($written['usage']['model'] ?? ''), $context->idempotencyKey('ai-copy-'.$language.'-run'.$context->run->getId()), false);
            }
        }
        $context->log('Website copy written', ['languages' => $languages, 'fallback' => $fallback]);

        $customer = $project->getCustomer();
        $owner = $customer?->getEmail() ?? $project->getLead()?->getEmail();
        $generation = new GenerationRequest(
            $template,
            $project->getSlug(),
            (string) ($project->getBusinessName() ?? $project->getName()),
            $project->getRequirement()->getCity(),
            $project->getLocale(),
            $project->getFeatures(),
            $content,
            null !== $project->getDomainName() ? 'https://'.$project->getDomainName() : rtrim($this->appsUrl, '/').'/'.$project->getSlug(),
            (string) ($this->settings->get('generation')['currency'] ?? 'MAD'),
            $customer?->getPhone() ?? $project->getLead()?->getPhone(),
            $owner,
        );
        $directory = $this->buildsDir.'/'.$project->getSlug();
        $result = $this->generator->generate($generation, $directory);
        $context->log('Application generated', ['template' => $template, 'files' => \count($result->files), 'pages' => \count($result->pages), 'custom_features' => $result->coverage['custom']]);

        if (null === $this->credentials->find($project, 'app_admin') && null !== $owner) {
            $this->credentials->store($project, 'app_admin', 'Administration of your application', $owner, CredentialService::generatePassword());
        }

        [$provider, $driver] = $this->repository($project);
        $commit = $driver->commit($provider, RepositoryInfo::fromArray($repositoryData), $directory, \sprintf("Generate the %s application\n\nTemplate %s, %d files, languages: %s.\nGenerated by the Mzian.net Development Agent.", $project->getName(), $template, \count($result->files), implode(', ', $result->languages)));
        $this->em->flush();
        $context->log($commit->created ? 'Sources committed' : 'Sources unchanged (idempotent)', ['commit' => $commit->sha]);

        return new AgentResult(\sprintf('Application generated from the "%s" template (%d pages) and committed.', $template, \count($result->pages)), [
            'template' => $template,
            'build_dir' => $directory,
            'commit' => $commit->sha,
            'version' => substr($commit->sha, 0, 12),
            'files' => \count($result->files),
            'pages' => $result->pages,
            'languages' => $result->languages,
            'entities' => $result->entities,
            'coverage' => $result->coverage,
            'content_fallback' => $fallback,
        ]);
    }

    /**
     * @return array{0: Provider, 1: RepositoryProviderInterface}
     */
    private function repository(Project $project): array
    {
        $provider = $this->providers->resolve(ProviderType::Repository, $project);
        if (!$this->repositories->has($provider->getDriver())) {
            throw AgentException::permanent(\sprintf('No repository driver "%s" installed.', $provider->getDriver()));
        }

        return [$provider, $this->repositories->get($provider->getDriver())];
    }
}
